name: ci

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            canyon_network.tex
          latexmk_use_xelatex: true
